use_frameworks!

platform :ios, '8.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'MYImagePicker_Example' do
  pod 'MYImagePicker', :path => '../'

  target 'MYImagePicker_Tests' do
    inherit! :search_paths

    
  end
end
